import React from "react";
import {
	CircularProgress,
	Box,
	TextField,
	IconButton,
	InputAdornment,
} from "@mui/material";
import FileCopyIcon from "@mui/icons-material/FileCopy";

interface GPTResponseTextProps {
	GPTResponse: string;
	isWaiting: boolean;
}

const GPTResponseText: React.FC<GPTResponseTextProps> = ({
															 GPTResponse,
	isWaiting,
}) => {
	return (
		<Box
			sx={{
				display: "flex",
				flexDirection: "column",
				justifyContent: "center",
				alignItems: "center",
				m: "2rem auto",
				width: "95%",
			}}
		>
			{isWaiting ? (
				<CircularProgress />
			) : GPTResponse ? (
				GPTResponse.startsWith("https://") ? (
					<img
						src={GPTResponse}
						alt='Generated by GPT'
						style={{ width: "100%", height: "auto" }}
					/>
				) : (
					<TextField
						multiline
						fullWidth
						value={GPTResponse
							.split(" ")
							.reduce((acc: string, word: string, i: number) => {
								return acc + word + (i % 50 === 0 ? " " : " ");
							}, "")}
						inputProps={{
							readOnly: true,
						}}
						InputProps={{
							endAdornment: (
								<InputAdornment
									position='end'
									style={{ position: "absolute", right: 0, top: 20 }}
								>
									<IconButton
										onClick={() => navigator.clipboard.writeText(GPTResponse)}
									>
										<FileCopyIcon />
									</IconButton>
								</InputAdornment>
							),
						}}
					/>
				)
			) : null}
		</Box>
	);
};

export default GPTResponseText;
